---

- name: certbot dependencies installed
  apt: pkg=software-properties-common state=present update_cache=yes

- name: Add certbot repository from PPA and install its signing key.
  apt_repository: repo='ppa:certbot/certbot'

- name: certbot and nginx plugin installed
  apt: pkg=python-certbot-nginx state=present update_cache=yes

- name: Make directory for nginx config backup
  shell: cp -r /etc/nginx/sites-enabled/ /etc/nginx/sites-enabled-pre-certbot/

# Also for plone need to update this in nginx config:
#
#    set $vh_protocol "http";
#    set $vh_port "80";
#
# to:
#    set $vh_protocol "https";
#    set $vh_port "443";
#
# Otherwise Firefox & co complain about "mixed content"

# cronjobs already installed by the package!
